### ISSUE TITLE
Update intl

### ISSUE THREAD

**Issue by marcosradix** [fadhly-permata/flutter_money_formatter#29]
Please update the version of intl in pub to intl 0.16.1 or higher!

**Comment by carlosfiori** [comment]
+1

**Comment by murilosamuel** [comment]
+1

**Comment by Tabarek** [comment]
+1

**Comment by worldofsites** [comment]
+1

**Comment by fadhly-permata** [comment]
Hi, sorry for leaving this project for a long time. I will update this package next week.

**Comment by mmuttaqin** [comment]
still don't have the update :)

**Comment by sweetysmilez** [comment]
waiting for an update

**Comment by pppshiwen** [comment]
waiting for an update

**Comment by carlosfiori** [comment]
still don't have the update :)

**Comment by Prn-Ice** [comment]
Any temporary fix?

**Comment by nfortiz** [comment]
2/02/2021 no updates
I have problems installing some firebase packages :c due to intl version.
Please update this awesome package!

**Comment by Chappie74** [comment]
Please update

**Comment by worldofsites** [comment]
my workaround:
```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_money_formatter:
    git:
      url: git://github.com/anisalibegic/flutter_money_formatter.git

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
```
